org: joannewce6
app: ce6-group2-sls
service: ce6-group2-sls
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
      - sqs:
          arn: arn:aws:sqs:ap-southeast-1:255945442255:Grp2Queue
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures
resources:
  Resources:
    MyQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "Grp2Queue"
    SuperTopic:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: "MyCustomTopic"

plugins:
  - serverless-offline