org: joannewce6
app: ce6-group2-sls
service: ce6-group2-sls

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:              # change2, command out line 21,flw del code of 18-20 
            - MessageQueue
            - Arn
functions:
  sendToSQS:
    handler: index.sendToSQS #updated with handler name from module
    environment:
      SQS_QUEUE_URL: 
        Ref: MessageQueue

    events:
      - httpApi: #changed to httpApi
          path: / #send
          method: post

resources:
  Resources:
    MessageQueue:
      Type: AWS::SQS::Queue   #change3 removed double quote
      Properties:
        QueueName: Grp2Queue   #change4 removed double quote, add in below outputs:  